In [11]:
import networkx as nx
import numpy as np

G = nx.Graph()

embedding_dim = 4

G.add_node('father',embeddings=np.random.randn(embedding_dim))
G.add_node('mother',embeddings=np.random.randn(embedding_dim))
G.add_node('son',embeddings=np.random.randn(embedding_dim))
G.add_node('puppy',embeddings=np.random.randn(embedding_dim))
G.add_edge('father', 'mother',embeddings=np.random.randn(embedding_dim))
G.add_edge('father', 'son',embeddings=np.random.randn(embedding_dim))
G.add_edge('son', 'mother',embeddings=np.random.randn(embedding_dim))

In [14]:
for n in G.nodes:
    print(G.nodes[n]["embeddings"])

[-0.26061304 -0.53891111 -0.18298735 -0.3496054 ]
[-2.47622062  1.312488    0.15236366 -0.73695658]
[ 0.0086304  -0.24211314 -0.04127376 -0.89895252]
[-1.15509799  0.20101394  0.49529001 -0.90362901]


In [96]:
neighborhood = []
for neighbor in list(G.neighbors('father')):
    neighborhood.append(G.nodes[neighbor]['embeddings'])
    neighborhood.append(G.get_edge_data('father', neighbor)['embeddings'])

In [103]:
np.array(neighborhood)

array([[-0.17404142,  0.45400824, -1.68307435,  0.41286672],
       [-0.03019339,  0.89015479,  1.38621003, -1.09576312],
       [-0.40341525,  0.3718906 ,  0.11468926,  0.79627342],
       [-0.15989274, -1.83388057, -0.02694712, -0.65072983]])